version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports: 
      - 5672:5672
      - 15672:15672
      - 15674:15674
    networks:
      - gonpy_net
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: gonpy
    volumes:
      - "$PWD/rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: gonpy
    ports:
      - 27017:27017
    networks:
      - gonpy_net
    # 数据持久化
    volumes:
      - mongodb_volume:/data/db
    restart: always

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    networks:
      - gonpy_net
    environment:
     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
     ME_CONFIG_MONGODB_ADMINPASSWORD: gonpy
     ME_CONFIG_MONGODB_URL: mongodb://admin:gonpy@mongo:27017/
    depends_on:
      - mongo
    restart: always

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    networks:
      - gonpy_net
    volumes:
      - influxdb_volume:/var/lib/influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      # password 长度要大于8个字符
      DOCKER_INFLUXDB_INIT_PASSWORD: gonpygonpy
      DOCKER_INFLUXDB_INIT_ORG: myorg 
      DOCKER_INFLUXDB_INIT_BUCKET: mybucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: need-to-modify-this-token
    restart: always

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - 3001:3000
  #   networks:
  #     - gonpy_net
  #   volumes:
  #     - grafana_volume:/var/lib/grafana
  #   depends_on:
  #     - influxdb
  #   restart: always


networks:
  gonpy_net:
    driver: bridge

volumes:
  influxdb_volume:
  mongodb_volume:
  # grafana_volume:
